const MarketDataActionTypes = {
    FETCH_MARKET_ITEMS_START: 'FETCH_MARKET_ITEMS_START',
    FETCH_MARKET_ITEMS_SUCCESS: 'FETCH_MARKET_ITEMS_SUCCESS',
    FETCH_MARKET_ITEMS_FAILURE: 'FETCH_MARKET_ITEMS_FAILURE',

    FETCH_CURRENCY_SEARCH_START: 'FETCH_CURRENCY_SEARCH_START',
    FETCH_CURRENCY_SEARCH_SUCCESS: 'FETCH_CURRENCY_SEARCH_SUCCESS',
    FETCH_CURRENCY_SEARCH_FAILURE: 'FETCH_CURRENCY_SEARCH_FAILURE',
    
    SHOW_LOADER: 'SHOW_LOADER'
  }

  export default MarketDataActionTypes